Update scriptt

diff --git a/fast-import b/fast-import
--- a/fast-import
+++ b/fast-import
@@ -1,28 +1,45 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+exec 3<>/dev/tty
+read -u 3 -p "Этот скрипт уничтожит данные в базе keitaro, вы уверены что хотите продолжить (yes|no)" yn
+case $yn in
+    [Yy]*) ;;
+    [Nn]*) exit
+           ;;
+    * )    echo "Please answer yes or no."
+           exit
+           ;;
+esac
+
+mysql_command=$(mysql --execute='SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST WHERE COMMAND = "Query" AND DB = "keitaro"';)
+
+if [[ $mysql_command ]]; then
+    echo "База Keitaro уже используется другим процессом"
+    exit 1
+fi
 
 # CLI
 show_help() {
   echo "Usage $0 -f DUMP_FILE -d STRING [-a ASYNC_TABLE_NAMES] [-r REPLACE_FROM] [-t REPLACE_TO]"
-  echo "Example: $0 -f backup.sql.gz -d booking -a table_name|table2_name -f incorrect -t correct"
+  echo "Example: $0 -f backup.sql.gz -d booking -a \"table_name|table2_name\" -f incorrect -t correct"
   exit 1
 }
 
 start=`date`
 dumpFile=''
-dbName=''
+dbName='keitaro'
 asyncImports=''
 replaceFrom=''
 replaceTo=''
+none_interactive=''
 
-while getopts ":f:d:a:r:t:" opt; do
+while getopts ":f:d:a:r:t:none_interactive" opt; do
     case $opt in
         h)
             show_help
             exit 0
             ;;
         f)  dumpFile=$OPTARG
-            ;;
-        d)  dbName=$OPTARG
             ;;
         a)  asyncImports=$OPTARG
             ;;
@@ -33,9 +50,6 @@ while getopts ":f:d:a:r:t:" opt; do
         \? ) echo "Invalid option: $OPTARG" 1>&2
             show_help >&2
             ;;
-        : )  echo "Invalid option: $OPTARG requires an argument" 1>&2
-            show_help >&2
-            ;;  
     esac
 done
 
@@ -47,7 +61,8 @@ if [[ -z "${dumpFile}" ]]; then
 fi
 
 if test ! -f "$dumpFile"; then
-    echo "$1 does not exists"
+    echo "keitaro dump does not exists"
+    exit 1
 fi
 
 # prepare directory
@@ -68,7 +83,12 @@ echo $append > dump/append.sql
 cd dump/
 
 # unpack
-gzip -dc ../${dumpFile} | csplit -s -ftable - "/-- Table structure for table/" {*} 
+if gzip -dc ../${dumpFile} | csplit -s -ftable - "/-- Table structure for table/" {*}; then
+  echo 'Success split dump tables'
+else
+  echo -e '\e[31mDump tables split failed\e[0m'
+  exit 1
+fi
 
 replaceInFile() {
   if [[ ! -z "${replaceFrom}" ]] &&  [[ $replaceFrom != $replaceTo ]]; then
@@ -85,9 +105,12 @@ for file in `ls -1 table*`; do
 done
 
 # cleaning
-rm ../dump.sql prepend.sql append.sql head table*
+rm prepend.sql append.sql head table*
 
-# importing 
+# clean db
+mysql -e "DROP DATABASE $dbName; CREATE DATABASE $dbName"
+
+# importing
 mysql_import(){
   mysql $2 < $1
 }
@@ -96,16 +119,21 @@ for file in *; do
     mysql_import "$file" "$dbName" &
 
     tableName=${file%".sql"}
-    if [[ -z "$asyncImports" ]] || [[ ! "$tableName" =~ $asyncImports ]]; then
+    if [[ -z "$asyncImports" ]]; then
+      asyncImports="_clicks|_ref_|visitors"
+    fi
+    if [[ ! "$tableName" =~ $asyncImports ]]; then
       pids+=($!)
     fi
 done
 
-wait "${pids[@]}" 
+wait "${pids[@]}"
 
 # store end date to a variable
 end=`date`
 
-rm -rf ../dump
+rm -rf ../dump ../${dumpFile}
 
 echo "Some parts of the dump will be imported in background. "
+echo "$start"
+echo "$end"
