Update scriptt

diff --git a/fast-import b/fast-import
--- a/fast-import
+++ b/fast-import
@@ -5,37 +5,33 @@ force_import=false
 show_help() {
   echo "Usage $0 -F DUMP_FILE [-d DATABASE_NAME] [-a ASYNC_TABLE_NAMES] [-r REPLACE_FROM] [-t REPLACE_TO]"
   echo "Example: $0 -F backup.sql.gz -d booking -a \"table_name|table2_name\" -f incorrect -t correct"
-  echo "or simple run to use with default options"
-  echo "bash -F backup.sql.gz"
   exit 1
 }
 
 parse_options() {
-  while getopts "F:d:a:r:t:f" opt; do
-      case $opt in
-          h)
-              show_help
-              exit 0
-              ;;
-          F)  dump_path=$OPTARG
-              ;;
-          d)  db_name=$OPTARG
-              ;;
-          a)  asynchronously_imported_tables_regex=$OPTARG
-              ;;
-          r)  replace_table_prefix_from=$OPTARG
-              ;;
-          t)  replace_table_prefix_to=$OPTARG
-              ;;
-          f) force_import=true
-              ;;
-          \? ) echo "Invalid option: $OPTARG" 1>&2
-              show_help >&2
-              ;;
-      esac
+  while getopts ":A:K:U:P:F:S:ra:t:i:k:L:l:hvpsw" opt; do
+    case $opt in
+        h)
+            show_help
+            exit 0
+            ;;
+        F)  dump_path=$OPTARG
+            ;;
+        d)  db_name=$OPTARG
+            ;;
+        a)  asynchronously_imported_tables_regex=$OPTARG
+            ;;
+        r)  replace_table_prefix_from=$OPTARG
+            ;;
+        t)  replace_table_prefix_to=$OPTARG
+            ;;
+        f) force_import=true
+            ;;
+        \? ) echo "Invalid option: $OPTARG" 1>&2
+            show_help >&2
+            ;;
+    esac
   done
-
-  shift $((OPTIND -1))
 
   if [[ "$force_import" = false ]]; then
     exec 3<>/dev/tty
@@ -50,6 +46,7 @@ parse_options() {
     esac
   fi
 
+  ensure_options_are_valid
 }
 
 ensure_nobody_is_using_database() {
@@ -160,7 +157,6 @@ remove_dump_dir() {
 }
 
 parse_options
-ensure_options_are_valid
 ensure_nobody_is_using_database
 
 make_dump_dir
